//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AniEventHandlerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AniEventHandler), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("RegCallback", RegCallback);
		L.RegFunction("AniEventCallBack", AniEventCallBack);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AniEventHandler obj = (AniEventHandler)ToLua.CheckObject(L, 1, typeof(AniEventHandler));
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.RegCallback(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AniEventCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AniEventHandler obj = (AniEventHandler)ToLua.CheckObject(L, 1, typeof(AniEventHandler));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.AniEventCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

