//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Pomelo_DotNetClient_ClientProtocolTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Pomelo.DotNetClient.ClientProtocolType));
		L.RegVar("NORMAL", get_NORMAL, null);
		L.RegVar("TLS", get_TLS, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NORMAL(IntPtr L)
	{
		ToLua.Push(L, Pomelo.DotNetClient.ClientProtocolType.NORMAL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TLS(IntPtr L)
	{
		ToLua.Push(L, Pomelo.DotNetClient.ClientProtocolType.TLS);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Pomelo.DotNetClient.ClientProtocolType o = (Pomelo.DotNetClient.ClientProtocolType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

