//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Pomelo_DotNetClient_ServerTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Pomelo.DotNetClient.ServerType));
		L.RegVar("GATE", get_GATE, null);
		L.RegVar("CONNECTOR", get_CONNECTOR, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GATE(IntPtr L)
	{
		ToLua.Push(L, Pomelo.DotNetClient.ServerType.GATE);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CONNECTOR(IntPtr L)
	{
		ToLua.Push(L, Pomelo.DotNetClient.ServerType.CONNECTOR);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Pomelo.DotNetClient.ServerType o = (Pomelo.DotNetClient.ServerType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

